---
title: 'Ocean Changes'
author: Ben Harden
date: '2021-05-05'
level: 2
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/MzM4MTMyMTU4Mjgy/a/MzUwNjQ0NDYxMzMx/details
quiz_text: "Submit Factsheet"
---

Now that we've re-familiarized ourselves with some basic facts about climate change, we're going to take a deeper dive into the impact on the ocean. In this level, you will work in a small group to prepare a factsheet on a particular aspect of our changing oceans. 

**Please check Slack/Google Classroom for your group assignments and work together with your team through this level. You will only need to submit one document per group**

## Exercise

You will be assigned one of the following topic to research:

* Ocean heat waves
* Expanding Oxygen Minimum Zones
* Thermohaline slowdown
* Ocean Acidification
* Coral Bleeching

Your goal is to produce a one-page fact sheet on your topic that will include information on the following:

* Basic information on what the process is
* How is it being driven (or predicted to be driven) by a changing climate?
* What observations do we already have of this process in action (past or present)?
* How well do scientists understand the processes? What is still unknown?
* What impacts will this process have (or is already having) on ecosystems and humans?

You fact-sheet can include images and you should cite your sources at the bottom. Creditable websites are fine sources for this exercise.

We are going to gather all of these fact sheets together by the end of the day **Tuesday June 8**. After your instructors check them for accuracy they will then be made available to all students to review. Our [small-group discussions](/discussions/) on June 10 will be on these fact sheets. Details for this discussion will be posted in Level 3.

Please submit one fact sheet per group at the assignment link below. All group members should then fill out an Exit Ticket.