---
title: "Phytoplankton 101"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
quiz: https://docs.google.com/forms/d/e/1FAIpQLSf7Zz7rEL83t8jAjV1gI7AaYeZdF7Rm4sJnb2DscypG4FdNUA/viewform?usp=sf_link
quiz_text: "Test Your Understanding"
---

Phytoplankton are the base of many food webs in the ocean. They are single-celled plant-like organisms that typically get their energy from sunlight. They exists throughout the world's oceans, primarily in the upper sunlit portion.

In this topic we are going to familiarize ourselves with phytoplankton and explore some of the factors that affect their abundance and geographic distribution.

## Reading

To get started, let's learn about what they are and what they need.

Watch this accessible intro to phytoplankton

<iframe width="800" height="450" src="https://www.youtube.com/embed/fS422O4SLc4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Read the following from [Segar](https://www.reefimages.com/oceansci.php):

* [Chapter 12](https://www.reefimages.com/oceans/SegarOcean4Chap12.pdf): only pg 287 - 296 (up to the end of the "Iron" section).

## Test Your Understanding

Take the following quiz to check your understanding. You can move on to [Level 2](../level-2/) if you get 4 or more correct. If not, please review the content, ask your peers for help, and retake quiz.

Once you're done with the quiz, click the "Level Complete" button to tell your instructors that you've completed the level.
